---
- name: Sample
  hosts: localhost
  tasks:
    - name: Create EC2 server
      ec2:
        image: "{{ ami_id }}"
        wait: yes
        instance_type: t2.micro
        region: "{{ region }}"
        group_id: "{{ security_groupid }}"
        vpc_subnet_id: "{{ subnet_id }}"
        key_name: "{{ keypair_name  }}"
        count_tag:
          Name: webserver
        exact_count: 2

    keypair_name: "muraliKP"
    subnet_id: "subnet-5716f03e"
    security_groupid: "sg-04cfc0e8827610275"
    region: "ap-south-1"   
    ami_id: "ami-02e60be79e78fef21"